====New round====
Black,White,Score,Error
2019woconnel,2019egan,22,'2018-02-27 20:13:38,568:DEBUG:[JAILED]:Listed student folders successfully\n2018-02-27 20:13:38,568:DEBUG:[JAILED]:Got data 2019egan 5.0 o ???????????@@@@o@@@??@@@@@@@@??@o@o@@@@??@@o@@o@@??@@@oo@o@??@@oooo@@??@@@@@@o@??o@.o@@oo???????????\n2018-02-27 20:13:38,568:DEBUG:[JAILED]:Data is ok\n2018-02-27 20:13:43,600:INFO:[JAILED]:There was no error thrown\n2018-02-27 20:13:43,600:DEBUG:[JAILED]:Got move 83\n'
2019egan,2019woconnel,-100,'2018-02-27 20:10:55,642:DEBUG:[JAILED]:Listed student folders successfully\n2018-02-27 20:10:55,642:DEBUG:[JAILED]:Got data 2019egan 5.0 @ ???????????........??...oo@..??...oo...??@@@@@o@@??..ooo.o.??.o@@@...??...@@...??...@....???????????\n2018-02-27 20:10:55,642:DEBUG:[JAILED]:Data is ok\n'
2018agurung,2019nanand,-100,'2018-02-27 20:17:16,905:DEBUG:[JAILED]:Listed student folders successfully\n2018-02-27 20:17:16,905:DEBUG:[JAILED]:Got data 2018agurung 5.0 @ ???????????........??........??........??...o@...??...@o...??........??........??........???????????\n2018-02-27 20:17:16,906:DEBUG:[JAILED]:Data is ok\nTraceback (most recent call last):\n  File "/home/othello/tourney/run_ai_jailed.py", line 106, in <module>\n    JailedAIServer(possible_names).run()\n  File "/home/othello/tourney/run_ai_jailed.py", line 68, in run\n    self.handle(sys.stdin, sys.stdout, sys.stderr, None)\n  File "/home/othello/tourney/run_ai_jailed.py", line 53, in handle\n    strat = self.AIClass(name, possible_names)\n  File "/home/othello/tourney/run_ai.py", line 59, in __init__\n    self.strat, self.new_path, self.new_sys = get_strat(self.name)\n  File "/home/othello/tourney/run_ai.py", line 36, in get_strat\n    strat = importlib.import_module(\'students.\'+name+\'.strategy\').\\\n  File "/home/othello/tourney/students/2018agurung/strategy.py", line 34, in __init__\n    self.model = load_model(\'2018agurung_model.txt\')\n  File "/home/othello/tourney/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/models.py", line 240, in load_model\n    with h5py.File(filepath, mode=\'r\') as f:\n  File "/home/othello/tourney/anaconda3/lib/python3.6/site-packages/h5py/_hl/files.py", line 269, in __init__\n    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)\n  File "/home/othello/tourney/anaconda3/lib/python3.6/site-packages/h5py/_hl/files.py", line 99, in make_fid\n    fid = h5f.open(name, flags, fapl=fapl)\n  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper\n  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper\n  File "h5py/h5f.pyx", line 78, in h5py.h5f.open\nOSError: Unable to open file (unable to open file: name = \'2018agurung_model.txt\', errno = 2, error message = \'No such file or directory\', flags = 0, o_flags = 0)\n'
2019nanand,2018agurung,100,'2018-02-27 20:17:17,105:DEBUG:[JAILED]:Listed student folders successfully\n2018-02-27 20:17:17,105:DEBUG:[JAILED]:Got data 2018agurung 5.0 o ???????????........??........??........??..@@@...??...@o...??........??........??........???????????\n2018-02-27 20:17:17,105:DEBUG:[JAILED]:Data is ok\nTraceback (most recent call last):\n  File "/home/othello/tourney/run_ai_jailed.py", line 106, in <module>\n    JailedAIServer(possible_names).run()\n  File "/home/othello/tourney/run_ai_jailed.py", line 68, in run\n    self.handle(sys.stdin, sys.stdout, sys.stderr, None)\n  File "/home/othello/tourney/run_ai_jailed.py", line 53, in handle\n    strat = self.AIClass(name, possible_names)\n  File "/home/othello/tourney/run_ai.py", line 59, in __init__\n    self.strat, self.new_path, self.new_sys = get_strat(self.name)\n  File "/home/othello/tourney/run_ai.py", line 36, in get_strat\n    strat = importlib.import_module(\'students.\'+name+\'.strategy\').\\\n  File "/home/othello/tourney/students/2018agurung/strategy.py", line 34, in __init__\n    self.model = load_model(\'2018agurung_model.txt\')\n  File "/home/othello/tourney/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/models.py", line 240, in load_model\n    with h5py.File(filepath, mode=\'r\') as f:\n  File "/home/othello/tourney/anaconda3/lib/python3.6/site-packages/h5py/_hl/files.py", line 269, in __init__\n    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)\n  File "/home/othello/tourney/anaconda3/lib/python3.6/site-packages/h5py/_hl/files.py", line 99, in make_fid\n    fid = h5f.open(name, flags, fapl=fapl)\n  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper\n  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper\n  File "h5py/h5f.pyx", line 78, in h5py.h5f.open\nOSError: Unable to open file (unable to open file: name = \'2018agurung_model.txt\', errno = 2, error message = \'No such file or directory\', flags = 0, o_flags = 0)\n'
